--Scripts de BD
--COMANDO PARA CREAR BASES DE DATOS
--CREATE DATABASE example;

--COMANDO PARA CREAR UNA TABLA;
--USE example;
--go

--DROP TABLE dbo.Users

--USE example
--go

CREATE TABLE dbo.Users(
	Id int NOT NULL PRIMARY KEY IDENTITY (1, 1),
	Address VARCHAR (300) NULL,
	Email VARCHAR (100) NOT NULL,
	FirstName VARCHAR (100) NOT NULL,
	LastName VARCHAR (100) NOT NULL,
	PhoneNumber VARCHAR (13) NULL,
	Username VARCHAR (100) NOT NULL,
    PasswordHash VARCHAR(256) NOT NULL,
    PasswordSalt VARCHAR(128) NOT NULL
)

--AÑADIR COLUMNAS NUEVAS
-- ALTER TABLE dbo.Users
-- ADD Username VARCHAR(100),
--     PasswordHash VARCHAR(256),
--     PasswordSalt VARCHAR(128);

--COMANDO PARA RENOMBRAR COLUMNAS
--EXEC sp_rename 'User.Telephone', 'PhoneNumber', 'COLUMN';

--COMANDO PARA ELIMINAR COLUMNAS
--ALTER TABLE dbo.Users
--DROP COLUMN Password;

--COMANDO PARA ALTERAR COLUMNAS
--ALTER TABLE dbo.Users
--ALTER COLUMN PhoneNumber VARCHAR(20);

--COMANDOS PARA VISUALIZAR LA INFORMACION
SELECT * FROM dbo.Users;
